name: netwealth
description: NetWealth is a blockchain project with a powerful API designed to support a wide range of use cases, enabling seamless integration and interaction with various applications and services.
version: 0.0.1
repository: https://github.com/MrVistos/netwealth

environment:
  sdk: ^3.4.3

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  lints: ^3.0.0